### ISSUE TITLE
Error in quoting picture label.

### ISSUE THREAD

**Issue by WXin2865896370** [NemoYuan2008/SJTU-Thesis-Proposal#2]
When I use the \ref command to refer to a picture after inserting the picture, the hyperlink gives an error. The information is as follows.
Package hyperref Warning: Suppressing link with empty target on input line 6.
Result:There are no hyperlinks to pictures in the compiled paragraph text.
<img width="182" alt="Snipaste_2024-12-27_13-38-51" src="https://github.com/user-attachments/assets/5c29cbeb-9272-4cfb-905e-5e17e16b072d" />
I tried to adjust the compilation order of macro packages, but I still have this problem.

**Comment by NemoYuan2008** [comment]
I could not reproduce your problem, could you provide a full example?

I tried the following code, inserted directly into the first section:
```tex
\begin{figure}
    \centering
    \includegraphics[width=10cm]{figures/sjtu-logo.png}
    \caption{交通大学的标志}
    \label{fig:sjtu-logo}
\end{figure}

如图 \ref{fig:sjtu-logo} 所示，这是交通大学的标志。
```
and it worked well, no compiler warnings. The generated hyperlink is clickable.
<img width="265" alt="image" src="https://github.com/user-attachments/assets/85d55660-5e9f-43ad-8031-ae843377b53a" />

**Comment by WXin2865896370** [comment]
![图片](https://github.com/user-attachments/assets/6926d51c-e384-48be-99b2-b8f34cc208a6)
I use the XeLatex

**Comment by NemoYuan2008** [comment]
I can see that you are using `\autoref` from the package `hyperref`, did you configured the autoref name? It seems that it is not the problem of the template.

Try adding
```tex
\renewcommand*{\figureautorefname}{图}
```
to the document preamble.

**Comment by WXin2865896370** [comment]
I just found out the problem, because the macro package newclude I added earlier conflicts with the macro package hyperref, so I must compile newclude before the macro package hyperref, and this problem will be solved.
